services:
  test:
    container_name: hwserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7264:7264"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - kernel_bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: []

networks:
  kernel_bridge:
    external: true
