name: Build, Test and Publish Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
        contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true


      - name: Poetry Install
        run: |
          poetry install

      - name: Run Tests
        run: |
          poetry run python -m pytest -v --disable-warnings --tb=short

  docs_update:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pages: write
    steps:
      - name: Checkout docs code
        uses: actions/checkout@v4
        with:
          repository: A-Team-Name/docs
          token: ${{ secrets.WRITE_TOKEN }}
      - name: update submodules
        run: git submodule update --init --recursive
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}
      - name: Push to main branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Update docs" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}

  build:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest
